/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AgentsAgentIdRouteImport } from "./routes/agents/$agentId"
import { Route as SessionsIndexRouteImport } from "./routes/sessions/index"
import { Route as SessionsSessionIdRouteImport } from "./routes/sessions/$sessionId"

const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: "/agents/$agentId",
  path: "/agents/$agentId",
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: "/sessions/",
  path: "/sessions/",
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: "/sessions/$sessionId",
  path: "/sessions/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/agents/$agentId": typeof AgentsAgentIdRoute
  "/sessions/$sessionId": typeof SessionsSessionIdRoute
  "/sessions/": typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  "/agents/$agentId": typeof AgentsAgentIdRoute
  "/sessions/$sessionId": typeof SessionsSessionIdRoute
  "/sessions": typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/agents/$agentId": typeof AgentsAgentIdRoute
  "/sessions/$sessionId": typeof SessionsSessionIdRoute
  "/sessions/": typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/agents/$agentId" | "/sessions/$sessionId" | "/sessions/"
  fileRoutesByTo: FileRoutesByTo
  to: "/agents/$agentId" | "/sessions/$sessionId" | "/sessions"
  id: "__root__" | "/agents/$agentId" | "/sessions/$sessionId" | "/sessions/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/agents/$agentId": {
      id: "/agents/$agentId"
      path: "/agents/$agentId"
      fullPath: "/agents/$agentId"
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sessions/": {
      id: "/sessions/"
      path: "/sessions"
      fullPath: "/sessions/"
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sessions/$sessionId": {
      id: "/sessions/$sessionId"
      path: "/sessions/$sessionId"
      fullPath: "/sessions/$sessionId"
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
